version: "2"
services:
 mysql:
  image: mysql:5.6
  mem_limit: 512m
  environment:
   #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   MYSQL_ROOT_PASSWORD: 'password'
   #MYSQL_ROOT_HOST: '%'
   #MYSQL_USER: 'enspirea'
   #MYSQL_PASSWORD: '820davis'
   #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #networks:
  # mynet:
  #  ipv4_address: 172.25.0.2
  #expose:
  # - 3306
  ports:
   - '3306:3306'
  volumes:
   - /etc/localtime:/etc/localtime

