# Generated by Django 3.0.2 on 2020-02-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prediction_is_higher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='is_higher',
            field=models.BooleanField(default=False),
        ),
    ]
