# Generated by Django 3.0.3 on 2020-04-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200224_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='high_value',
        ),
        migrations.AddField(
            model_name='prediction',
            name='actual',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predicted',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='previous',
            field=models.FloatField(default=0.0),
        ),
    ]
